[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BioAlignments = "00701ae9-d1dc-5365-b64a-a3a3ebf5695e"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FastaIO = "a0c94c4b-ebed-5953-b5fc-82fe598ac79f"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
PairwiseListMatrices = "f9da4da7-9382-5435-b973-175f5d8dfb32"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
ROCAnalysis = "f535d66d-59bb-5153-8d2b-ef0a426c6aff"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
Documenter = "1"
